### ISSUE TITLE
Encountering “ld: symbol(s) not found for architecture x86_64” Error on M1 MacBook with cmake .. && cmake --build . --parallel 4 && cd ..

### ISSUE THREAD

**Issue by wwwxuzhenyu** [nota-github/MLC-VLM-template#5]
I am facing an issue while compiling a project on my M1 MacBook. When executing the command cmake .. && cmake --build . --parallel 4 && cd .., I encounter the following error:

> Undefined symbols for architecture x86_64:
>   "_byte_level_bpe_tokenizers_new_from_str", referenced from:
>       tokenizers::Tokenizer::FromBlobByteLevelBPE(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_decode", referenced from:
>       tokenizers::HFTokenizer::Decode(std::__1::vector<int, std::__1::allocator<int>> const&, bool) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_encode", referenced from:
>       tokenizers::HFTokenizer::Encode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_encode_batch", referenced from:
>       tokenizers::HFTokenizer::EncodeBatch(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_free", referenced from:
>       tokenizers::HFTokenizer::~HFTokenizer() in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>       tokenizers::HFTokenizer::~HFTokenizer() in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_free_encode_results", referenced from:
>       tokenizers::HFTokenizer::Encode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>       tokenizers::HFTokenizer::EncodeBatch(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_get_decode_str", referenced from:
>       tokenizers::HFTokenizer::Decode(std::__1::vector<int, std::__1::allocator<int>> const&, bool) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_get_vocab_size", referenced from:
>       tokenizers::HFTokenizer::GetVocabSize() in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_id_to_token", referenced from:
>       tokenizers::HFTokenizer::IdToToken(int) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_new_from_str", referenced from:
>       tokenizers::Tokenizer::FromBlobJSON(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
>   "_tokenizers_token_to_id", referenced from:
>       tokenizers::HFTokenizer::TokenToId(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libtokenizers_cpp.a[3](huggingface_tokenizer.cc.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I would like to know if this repository supports M1 MacBook, or if there might be any errors in my installation process. Thank you!

**Comment by JLake310** [comment]
Hi @wwwxuzhenyu ,
Currently, I cannot reproduce your error on M1 Mac.

But it seems to be the problem of 3rdparty(tokenizer).
Can you try `git submodule sync && git submodule update --init` and make again?

**Comment by JLake310** [comment]
Since there has been no response for an extended period, we are respectfully closing this issue.
