### ISSUE TITLE
TVMError: Check failed (partial_update) is false: Key "image_token_index" not found

### ISSUE THREAD

**Issue by NSTiwari** [nota-github/MLC-VLM-template#6]
Hi, I've been following your tutorial to compile Llava 1.5 7B VLM and I was able to compile everything successfully. However, when I run the app, I get the following error:

![image](https://github.com/user-attachments/assets/33a59922-d005-4910-83a9-0553ef6436c0)

Here's my mlc-chat-config.json file. 
[mlc-chat-config.json](https://github.com/user-attachments/files/17174373/mlc-chat-config.json)

Can you please help me what has gone wrong?

**Comment by NSTiwari** [comment]
@JLake310 can you please check?

**Comment by NSTiwari** [comment]
Thank you, @JLake310.

As suggested, I have updated the `mlc-chat-config.json` by adding the `image_token_index` in the `conv_template` dictionary.

However, the error persists.

**Comment by NSTiwari** [comment]
@JLake310: Now I'm getting this error. Seems like a shape mismatch in the tensors. 

Could you please suggest what change is needed?

![IMG-20241006-WA0007](https://github.com/user-attachments/assets/d4a75ad5-3485-440c-b8d3-c710aede3df0)

**Comment by JLake310** [comment]
@NSTiwari 

It seems you're using LLaVA which use image size 336*336.
There're couple of things you need to change as we're targeting 224*224.

First, you need to change shape to `{1, 3, 336, 336}` at below
https://github.com/nota-github/MLC-VLM-template/blob/7df1b642a8d8e5c8dcf520c7a97bd88c84f0d258/android/library/src/main/java/ai/mlc/mlcllm/ChatModule.java#L44-L52

Second, set `hh, ww` to `336f`, and fix return line to `return scaleSize(bitmap, 336, 336)` at below.
https://github.com/nota-github/MLC-VLM-template/blob/7df1b642a8d8e5c8dcf520c7a97bd88c84f0d258/android/app/src/main/java/ai/mlc/mlcchat/ChatView.kt#L196-L222

I hope these could help you :)

**Comment by NSTiwari** [comment]
Thanks again, @JLake310. That resolved the error, but unfortunately, the phone I'm testing on is not capable enough to run Llava. Do you know any other light-weight model that I can try?

**Comment by JLake310** [comment]
@NSTiwari , 

You may try with PhiVA, a model developed in-house by our company for lightweight modeling.
(* The model is still under debugging due to an issue where incorrect responses are returned on some devices.)

If you need any additional information about PhiVA, please refer to this [article](https://www.nota.ai/community/deploying-an-efficient-vision-language-model-on-mobile-devices).

Here's the way that you can deploy PhiVA on your device.

1. Package the libraries with below script.

```bash
set -e

MODEL_NAME=phiva-4b-hf-q4f16_1-MLC
QUANTIZATION=q4f16_1

# 1. Download converted weights from HF
git lfs install
git clone https://huggingface.co/nota-ai/${MODEL_NAME}-${QUANTIZATION}-MLC \
          ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC
          
# 2. compile model library with specification in mlc-chat-config.json
mlc_llm compile ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/mlc-chat-config.json \
    --device android -o ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/${MODEL_NAME}-${QUANTIZATION}-android.tar

# 3. Generate model execution logics
cd android/library
chmod +x prepare_libs.sh
bash prepare_libs.sh
```

2. Change image size 336 to 224 following my comment above.

Also, It would also be appreciated if you could provide information about your device in your response.

**Comment by kacel33** [comment]
> @NSTiwari Sorry for the late response. It seems to be an error while loading the configs. The simplest modification would be move `image_token_index` field from model_config to `conv_template` dict.
> 
> [mlc-chat-config.json](https://github.com/user-attachments/files/17255880/mlc-chat-config.json) Please run the app with the modified config file.
> 
> And I'll fix the config generation step so that you would not encounter same error again. I apologize for the late check again.

I encountered the same error, and it's still not resolved. After modifying the config file and running the following commands:

mlc_llm compile ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/mlc-chat-config.json \
    --device android -o ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/${MODEL_NAME}-${QUANTIZATION}-android.tar

# 5. Generate model execution logics
cd android/library
chmod +x prepare_libs.sh
bash prepare_libs.sh

Where could the problem be?

**Comment by kacel33** [comment]
> @NSTiwari Sorry for the late response. It seems to be an error while loading the configs. The simplest modification would be move `image_token_index` field from model_config to `conv_template` dict.
> 
> [mlc-chat-config.json](https://github.com/user-attachments/files/17255880/mlc-chat-config.json) Please run the app with the modified config file.
> 
> And I'll fix the config generation step so that you would not encounter same error again. I apologize for the late check again.

I encountered the same error, and it's still not resolved. After modifying the config file and running the following commands:

mlc_llm compile ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/mlc-chat-config.json
--device android -o ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/${MODEL_NAME}-${QUANTIZATION}-android.tar

cd android/library
chmod +x prepare_libs.sh
bash prepare_libs.sh

Where could the problem be?

**Comment by JLake310** [comment]
Hi @kacel33 ,

Did you change the `mlc-chat-config.json` in your local device?
You may find mlc-chat-config.json at `/storage/emulated/0/Android/data/ai.mlc.mlcchat/files/{model_dir}/`.

**Comment by NSTiwari** [comment]
Hi @JLake310 
Just curious, would this support PaliGemma 3B model?

**Comment by JLake310** [comment]
Hi @NSTiwari ,
I didn't tried PaliGemma before but,
SigLIP is not implemented in this repository so it might not work.

**Comment by NSTiwari** [comment]
> Hi @NSTiwari , I didn't tried PaliGemma before but, SigLIP is not implemented in this repository so it might not work.

Hi @JLake310, just revisiting this:
I can see in [MLC-Imp](https://github.com/MILVLG/mlc-imp), the Imp model is based on SigLIP vision encoder. So, does that help running the same for PaliGemma?
